[package]
name = "issh-sftp"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "issh SFTP 附件传输层（M4 实现）"

[dependencies]
issh-types = { workspace = true }
issh-ssh = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true }
